TILE_SCALING = 1.5

TILE_SIZE = 16
TILE_SCALED_SIZE = TILE_SIZE * TILE_SCALING
MAP_WIDTH = 28
MAP_HEIGHT = 32

WINDOW_WIDTH = MAP_WIDTH * TILE_SCALED_SIZE
WINDOW_HEIGHT = MAP_HEIGHT * TILE_SCALED_SIZE

PLAYER_SPAWN_TILE_X = 13
PLAYER_SPAWN_TILE_Y = 6

DEFAULT_MOB_SPEED = 2

MOB_DEFAULT_WIDTH = TILE_SCALED_SIZE + 4
MOB_DEFAULT_HEIGHT = TILE_SCALED_SIZE + 8

PLAYER_MOVE_ANIMATION_FRAMES = 8

SCORE_X = 7 * TILE_SCALED_SIZE
SCORE_Y = 3 * TILE_SCALED_SIZE
FONT_SIZE = TILE_SCALED_SIZE / 2

